In [1]:
import numpy as np

In [8]:
lst = np.arange(27)
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
lst.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [10]:
import cv2

In [22]:
img = cv2.imread("smallgray.png", 1)
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [25]:
img2 = cv2.imwrite("newsamllgray.png", img)
img2

True

In [28]:
img[1, 4, :]

array([147, 147, 147], dtype=uint8)

In [31]:
for n in img[1, :, :].flat:
    print(n)

198
198
198
125
125
125
255
255
255
255
255
255
147
147
147


In [32]:
for n in img[1, :, :]:
    print(n)

[198 198 198]
[125 125 125]
[255 255 255]
[255 255 255]
[147 147 147]


In [35]:
np.hstack([img, img])

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143],
        [187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147],
        [198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182],
        [209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [36]:
np.vstack([img, img])

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]],

       [[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [56]:
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [53]:
np.hsplit(img, 5)

[array([[[187, 187, 187]],
 
        [[198, 198, 198]],
 
        [[209, 209, 209]]], dtype=uint8),
 array([[[158, 158, 158]],
 
        [[125, 125, 125]],
 
        [[134, 134, 134]]], dtype=uint8),
 array([[[104, 104, 104]],
 
        [[255, 255, 255]],
 
        [[255, 255, 255]]], dtype=uint8),
 array([[[121, 121, 121]],
 
        [[255, 255, 255]],
 
        [[ 97,  97,  97]]], dtype=uint8),
 array([[[143, 143, 143]],
 
        [[147, 147, 147]],
 
        [[182, 182, 182]]], dtype=uint8)]

In [57]:
np.vsplit(img, 3)

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]]], dtype=uint8),
 array([[[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]]], dtype=uint8),
 array([[[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8)]